export const WORDS = [
  "ACORN", "AMBER", "APPLE", "ARROW", "ATLAS", "BADGER", "BAMBOO", "BANANA", "BEACON", "BEAVER",
  "BERRY", "BIRCH", "BONSAI", "BREEZE", "CACTUS", "CANYON", "CASTLE", "CEDAR", "CHERRY", "CLOVER",
  "COAL", "COCOA", "COPPER", "COSMOS", "CRATER", "DAISY", "DESERT", "DOVE", "EAGLE", "EARTH",
  "EMBER", "FALCON", "FERN", "FOREST", "FROST", "GALAXY", "GECKO", "GLACIER", "GOLDEN", "GRAPE",
  "HAVEN", "HAWK", "HAZEL", "HEATHER", "HONEY", "ICEBERG", "IRIS", "IVY", "JASPER", "JUNIPER",
  "KESTREL", "KIWI", "LAGOON", "LEMON", "LICHEN", "LOTUS", "LUPINE", "MAPLE", "MARBLE", "MEADOW",
  "MELON", "MINT", "MIRAGE", "MOON", "MOSS", "NECTOR", "OAK", "OASIS", "OLIVE", "ONYX",
  "ORANGE", "ORCHID", "OTTER", "PEACH", "PEAR", "PEBBLE", "PINE", "PLUM", "QUARTZ", "RADAR",
  "RAIN", "RIVER", "ROSE", "SABLE", "SAFFRON", "SAGE", "SAND", "SHADOW", "SIERRA", "SNOW",
  "STAR", "STONE", "SUMMIT", "SUN", "TIGER", "TULIP", "VALLEY", "VOLCANO", "WAVE", "WIND"
];
